version: 2
jobs:
   build:
     docker:
       - image: docker:17.05.0-ce-git
     steps:
       - checkout
       - setup_remote_docker:
            docker_layer_caching: true
       - run: docker build -t anthony/test .
       - run: docker run --rm anthony/test echo test
